CREATE TABLE corrections (
    id SERIAL PRIMARY KEY,
    text VARCHAR(255),
    type VARCHAR(100)
);

INSERT INTO corrections (text, type) VALUES 
    ('Business analytics', 'skill'),
    ('Business maturity', 'skill'),
    ('Strategy', 'skill'),
    ('Non-technical and technical communication', 'skill'),
    ('Algorithms & datastrucures', 'skill'),
    ('Software Engineering', 'skill'),
    ('Detail oriented', 'skill'),
    ('Creative thinker', 'skill'),
    ('Problem solving', 'skill'),
    ('Critical thinking', 'skill'),
    ('Team player', 'skill'),
    ('Time management', 'skill'),
    ('Adaptability', 'skill'),
    ('Conflict resolution', 'skill'),
    ('Collaborative', 'skill'),
    ('Dilligent', 'skill'),
    ('Software development', 'skill'),
    ('ITIL', 'skill'),
    ('SAFe', 'skill'),
    ('PRINCE2', 'skill'),
    ('CMMI', 'skill'),
    ('SCRUM', 'skill'),
    ('Agile development', 'skill'),
    ('UML', 'skill'),
    ('Stakeholder classification', 'skill'),
    ('Python', 'skill'),
    ('SQL', 'skill'),
    ('R', 'skill'),
    ('JavaScript', 'skill'),
    ('Git', 'skill'),
    ('Statistical modelling', 'skill'),
    ('Fundamental Azure knowledge', 'skill'),
    ('PostGres', 'skill'),
    ('Neo4J', 'skill'),
    ('Qdrant', 'skill'),
    ('ANNOY', 'skill'),
    ('Docker', 'skill'),
    ('scraping', 'skill'),
    ('crawling', 'skill'),
    ('MT5', 'skill'),
    ('Bert', 'skill'),
    ('FinBert', 'skill'),
    ('T5', 'skill'),
    ('Scrapy', 'skill'),
    ('Numpy', 'skill'),
    ('Polars', 'skill'),
    ('Pandas', 'skill'),
    ('FastAPI', 'skill'),
    ('VUE3', 'skill'),
    ('TensorFlow2', 'skill'),
    ('Huggingface', 'skill'),
    ('Pytorch', 'skill'),
    ('SonarCube', 'skill'),
    ('Matplotlib', 'skill'),
    ('Seaborn', 'skill'),
    ('Plotly', 'skill'),
    ('PyTest', 'skill'),
    ('SKlearn', 'skill'),
    ('Dimensionality Reduction', 'skill'),
    ('Explorative Factor Analysis', 'skill'),
    ('K-mean', 'skill'),
    ('Random Forests', 'skill'),
    ('Multiple logistic regression', 'skill'),
    ('SVP', 'skill'),
    ('NNs', 'skill'),
    ('Classification', 'skill');

INSERT INTO corrections (text, type) VALUES 
    ('abreast', 'word'),
    ('ardent', 'word'),
    ('cruisal', 'word'),
    ('deeply', 'word'),
    ('dvelve', 'word'),
    ('devising', 'word'),
    ('eager', 'word'),
    ('eagerly', 'word'),
    ('endeavors', 'word'),
    ('enthusiastic', 'word'),
    ('excited', 'word'),
    ('excel', 'word'),
    ('extensive', 'word'),
    ('extensively', 'word'),
    ('expert', 'word'),
    ('expertise', 'word'),
    ('facets', 'word'),
    ('foster', 'word'),
    ('forefront', 'word'),
    ('fostering', 'word'),
    ('fueled', 'word'),
    ('fulfilling', 'word'),
    ('honed', 'word'),
    ('intricacies', 'word'),
    ('intricate', 'word'),
    ('meticulous', 'word'),
    ('perfect', 'word'),
    ('perfectly', 'word'),
    ('prowess', 'word'),
    ('profoundly', 'word'),
    ('prospect', 'word'),
    ('realm', 'word'),
    ('seamlessly', 'word'),
    ('specialist', 'word'),
    ('stems', 'word'),
    ('strive', 'word'),
    ('striving', 'word'),
    ('superior', 'word'),
    ('superiority', 'word'),
    ('Tableau', 'word'),
    ('thrilled', 'word'),
    ('versed', 'word');

INSERT INTO corrections (text, type) VALUES 
    ('I am a perfect fit for this role', 'sentence'),
    ('which is crucial', 'sentence'),
    ('crucial for this role', 'sentence'),
    ('perfectly aligned', 'sentence'),
    ('perfectly suited', 'sentence'),
    ('perfectly align', 'sentence'),
    ('which are essential for', 'sentence'),
    ('which are essential for this role', 'sentence'),
    ('mathematical modelin', 'sentence'),
    ('make me a suitable candidate for this role', 'sentence'),
    ('makes me a suitable candidate for this role', 'sentence'),
    ('make me a great fit for this role', 'sentence'),
    ('makes me a great fit for this role', 'sentence'),
    ('make me a strong fit for this position', 'sentence'),
    ('makes me a strong fit for this position', 'sentence'),
    ('make me a strong candidate for this role', 'sentence'),
    ('makes me a strong candidate for this role', 'sentence'),
    ('positions me well for this role', 'sentence'),
    ('invaluable in driving innovative AI solutions', 'sentence'),
    ('makes me a strong candidate for this role', 'sentence'),
    ('which will be valuable for the companys projects', 'sentence'),
    ('will be beneficial in delivering data driven solutions', 'sentence');
