INSERT INTO corrections (id, text, type) VALUES 
    (uuid_generate_v4(), 'Business analytics', 'skill'),
    (uuid_generate_v4(), 'Business maturity', 'skill'),
    (uuid_generate_v4(), 'Strategy', 'skill'),
    (uuid_generate_v4(), 'Non-technical and technical communication', 'skill'),
    (uuid_generate_v4(), 'Algorithms & datastrucures', 'skill'),
    (uuid_generate_v4(), 'Software Engineering', 'skill'),
    (uuid_generate_v4(), 'Detail oriented', 'skill'),
    (uuid_generate_v4(), 'Creative thinker', 'skill'),
    (uuid_generate_v4(), 'Problem solving', 'skill'),
    (uuid_generate_v4(), 'Critical thinking', 'skill'),
    (uuid_generate_v4(), 'Team player', 'skill'),
    (uuid_generate_v4(), 'Time management', 'skill'),
    (uuid_generate_v4(), 'Adaptability', 'skill'),
    (uuid_generate_v4(), 'Conflict resolution', 'skill'),
    (uuid_generate_v4(), 'Collaborative', 'skill'),
    (uuid_generate_v4(), 'Dilligent', 'skill'),
    (uuid_generate_v4(), 'Software development', 'skill'),
    (uuid_generate_v4(), 'ITIL', 'skill'),
    (uuid_generate_v4(), 'SAFe', 'skill'),
    (uuid_generate_v4(), 'PRINCE2', 'skill'),
    (uuid_generate_v4(), 'CMMI', 'skill'),
    (uuid_generate_v4(), 'SCRUM', 'skill'),
    (uuid_generate_v4(), 'Agile development', 'skill'),
    (uuid_generate_v4(), 'UML', 'skill'),
    (uuid_generate_v4(), 'Stakeholder classification', 'skill'),
    (uuid_generate_v4(), 'Python', 'skill'),
    (uuid_generate_v4(), 'SQL', 'skill'),
    (uuid_generate_v4(), 'R', 'skill'),
    (uuid_generate_v4(), 'JavaScript', 'skill'),
    (uuid_generate_v4(), 'Git', 'skill'),
    (uuid_generate_v4(), 'Statistical modelling', 'skill'),
    (uuid_generate_v4(), 'Fundamental Azure knowledge', 'skill'),
    (uuid_generate_v4(), 'PostGres', 'skill'),
    (uuid_generate_v4(), 'Neo4J', 'skill'),
    (uuid_generate_v4(), 'Qdrant', 'skill'),
    (uuid_generate_v4(), 'ANNOY', 'skill'),
    (uuid_generate_v4(), 'Docker', 'skill'),
    (uuid_generate_v4(), 'scraping', 'skill'),
    (uuid_generate_v4(), 'crawling', 'skill'),
    (uuid_generate_v4(), 'MT5', 'skill'),
    (uuid_generate_v4(), 'Bert', 'skill'),
    (uuid_generate_v4(), 'FinBert', 'skill'),
    (uuid_generate_v4(), 'T5', 'skill'),
    (uuid_generate_v4(), 'Scrapy', 'skill'),
    (uuid_generate_v4(), 'Numpy', 'skill'),
    (uuid_generate_v4(), 'Polars', 'skill'),
    (uuid_generate_v4(), 'Pandas', 'skill'),
    (uuid_generate_v4(), 'FastAPI', 'skill'),
    (uuid_generate_v4(), 'VUE3', 'skill'),
    (uuid_generate_v4(), 'TensorFlow2', 'skill'),
    (uuid_generate_v4(), 'Huggingface', 'skill'),
    (uuid_generate_v4(), 'Pytorch', 'skill'),
    (uuid_generate_v4(), 'SonarCube', 'skill'),
    (uuid_generate_v4(), 'Matplotlib', 'skill'),
    (uuid_generate_v4(), 'Seaborn', 'skill'),
    (uuid_generate_v4(), 'Plotly', 'skill'),
    (uuid_generate_v4(), 'PyTest', 'skill'),
    (uuid_generate_v4(), 'SKlearn', 'skill'),
    (uuid_generate_v4(), 'Dimensionality Reduction', 'skill'),
    (uuid_generate_v4(), 'Explorative Factor Analysis', 'skill'),
    (uuid_generate_v4(), 'K-mean', 'skill'),
    (uuid_generate_v4(), 'Random Forests', 'skill'),
    (uuid_generate_v4(), 'Multiple logistic regression', 'skill'),
    (uuid_generate_v4(), 'SVP', 'skill'),
    (uuid_generate_v4(), 'NNs', 'skill'),
    (uuid_generate_v4(), 'Classification', 'skill');

INSERT INTO corrections (id, text, type) VALUES 
    (uuid_generate_v4(), 'abreast', 'word'),
    (uuid_generate_v4(), 'ardent', 'word'),
    (uuid_generate_v4(), 'cruisal', 'word'),
    (uuid_generate_v4(), 'deeply', 'word'),
    (uuid_generate_v4(), 'dvelve', 'word'),
    (uuid_generate_v4(), 'devising', 'word'),
    (uuid_generate_v4(), 'eager', 'word'),
    (uuid_generate_v4(), 'eagerly', 'word'),
    (uuid_generate_v4(), 'endeavors', 'word'),
    (uuid_generate_v4(), 'enthusiastic', 'word'),
    (uuid_generate_v4(), 'excited', 'word'),
    (uuid_generate_v4(), 'excel', 'word'),
    (uuid_generate_v4(), 'extensive', 'word'),
    (uuid_generate_v4(), 'extensively', 'word'),
    (uuid_generate_v4(), 'expert', 'word'),
    (uuid_generate_v4(), 'expertise', 'word'),
    (uuid_generate_v4(), 'facets', 'word'),
    (uuid_generate_v4(), 'foster', 'word'),
    (uuid_generate_v4(), 'forefront', 'word'),
    (uuid_generate_v4(), 'fostering', 'word'),
    (uuid_generate_v4(), 'fueled', 'word'),
    (uuid_generate_v4(), 'fulfilling', 'word'),
    (uuid_generate_v4(), 'honed', 'word'),
    (uuid_generate_v4(), 'intricacies', 'word'),
    (uuid_generate_v4(), 'intricate', 'word'),
    (uuid_generate_v4(), 'meticulous', 'word'),
    (uuid_generate_v4(), 'perfect', 'word'),
    (uuid_generate_v4(), 'perfectly', 'word'),
    (uuid_generate_v4(), 'prowess', 'word'),
    (uuid_generate_v4(), 'profoundly', 'word'),
    (uuid_generate_v4(), 'prospect', 'word'),
    (uuid_generate_v4(), 'realm', 'word'),
    (uuid_generate_v4(), 'seamlessly', 'word'),
    (uuid_generate_v4(), 'specialist', 'word'),
    (uuid_generate_v4(), 'stems', 'word'),
    (uuid_generate_v4(), 'strive', 'word'),
    (uuid_generate_v4(), 'striving', 'word'),
    (uuid_generate_v4(), 'superior', 'word'),
    (uuid_generate_v4(), 'superiority', 'word'),
    (uuid_generate_v4(), 'Tableau', 'word'),
    (uuid_generate_v4(), 'thrilled', 'word'),
    (uuid_generate_v4(), 'versed', 'word');

INSERT INTO corrections (id, text, type) VALUES 
    (uuid_generate_v4(), 'I am a perfect fit for this role', 'sentence'),
    (uuid_generate_v4(), 'which is crucial', 'sentence'),
    (uuid_generate_v4(), 'crucial for this role', 'sentence'),
    (uuid_generate_v4(), 'perfectly aligned', 'sentence'),
    (uuid_generate_v4(), 'perfectly suited', 'sentence'),
    (uuid_generate_v4(), 'perfectly align', 'sentence'),
    (uuid_generate_v4(), 'which are essential for', 'sentence'),
    (uuid_generate_v4(), 'which are essential for this role', 'sentence'),
    (uuid_generate_v4(), 'mathematical modelin', 'sentence'),
    (uuid_generate_v4(), 'make me a suitable candidate for this role', 'sentence'),
    (uuid_generate_v4(), 'makes me a suitable candidate for this role', 'sentence'),
    (uuid_generate_v4(), 'make me a great fit for this role', 'sentence'),
    (uuid_generate_v4(), 'makes me a great fit for this role', 'sentence'),
    (uuid_generate_v4(), 'make me a strong fit for this position', 'sentence'),
    (uuid_generate_v4(), 'makes me a strong fit for this position', 'sentence'),
    (uuid_generate_v4(), 'make me a strong candidate for this role', 'sentence'),
    (uuid_generate_v4(), 'makes me a strong candidate for this role', 'sentence'),
    (uuid_generate_v4(), 'positions me well for this role', 'sentence'),
    (uuid_generate_v4(), 'invaluable in driving innovative AI solutions', 'sentence'),
    (uuid_generate_v4(), 'which will be valuable for the companys projects', 'sentence'),
    (uuid_generate_v4(), 'will be beneficial in delivering data driven solutions', 'sentence');
