# Pull the official PostgreSQL image
FROM postgres:latest

# Set environment variables for PostgreSQL
ENV POSTGRES_DB=rel_db
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin

# Expose PostgreSQL port
EXPOSE 5432

# Copy the initialization SQL files if you have any
# COPY 
